DROP TABLE IF EXISTS `#__jzc_config`;

CREATE TABLE `#__jzc_config` (
  `id` INT(11) NOT NULL AUTO_INCREMENT
 ,`config_item` VARCHAR(32) NOT NULL
 ,`config_value` VARCHAR(32) NOT NULL
 , PRIMARY KEY  (`id`)
 , UNIQUE INDEX (`config_item`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `#__jzc_country`;

CREATE TABLE `#__jzc_country` (
  `id` INT(11) NOT NULL AUTO_INCREMENT
 ,`country_name` VARCHAR(64) NOT NULL
 ,`country_code` CHAR(2) NOT NULL
 ,`data_source` VARCHAR(64) DEFAULT NULL
 ,`data_prepared` VARCHAR(64) DEFAULT NULL
 ,`data_date` DATE NOT NULL DEFAULT '0000-00-00'
 ,`ordering` INT(2) NOT NULL DEFAULT '0'
 ,`published` TINYINT(1) NOT NULL DEFAULT '1'
 ,`checked_out` INT(11) UNSIGNED NOT NULL DEFAULT '0'
 ,`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00'
 , PRIMARY KEY  (`id`)
 , UNIQUE INDEX (`country_code`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `#__jzc_zipcode`;

CREATE TABLE `#__jzc_zipcode` (
  `id` INT(11) NOT NULL AUTO_INCREMENT
 ,`zip_code` VARCHAR(8) NOT NULL
 ,`latitude` DECIMAL(10,8)
 ,`longitude` DECIMAL(11,8)
 ,`country_code` CHAR(2) NOT NULL
 , PRIMARY KEY  (`id`)
 , UNIQUE INDEX (`zip_code`, `country_code`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

INSERT INTO `#__jzc_country` (`id`,`country_name`,`country_code`,`published`)
  VALUES
 (NULL,'Afghanistan','AF',0)
,(NULL,'Albania','AL',0)
,(NULL,'Algeria','DZ',0)
,(NULL,'American Samoa','AS',0)
,(NULL,'Andorra','AD',0)
,(NULL,'Angola','AO',0)
,(NULL,'Anguilla','AI',0)
,(NULL,'Antarctica','AQ',0)
,(NULL,'Antigua and Barbuda','AG',0)
,(NULL,'Argentina','AR',0)
,(NULL,'Armenia','AM',0)
,(NULL,'Aruba','AW',0)
,(NULL,'Australia','AU',0)
,(NULL,'Austria','AT',0)
,(NULL,'Azerbaijan','AZ',0)
,(NULL,'Bahamas','BS',0)
,(NULL,'Bahrain','BH',0)
,(NULL,'Bangladesh','BD',0)
,(NULL,'Barbados','BB',0)
,(NULL,'Belarus','BY',0)
,(NULL,'Belgium','BE',0)
,(NULL,'Belize','BZ',0)
,(NULL,'Benin','BJ',0)
,(NULL,'Bermuda','BM',0)
,(NULL,'Bhutan','BT',0)
,(NULL,'Bolivia','BO',0)
,(NULL,'Bosnia and Herzegowina','BA',0)
,(NULL,'Botswana','BW',0)
,(NULL,'Bouvet Island','BV',0)
,(NULL,'Brazil','BR',0)
,(NULL,'British Indian Ocean Territory','IO',0)
,(NULL,'Brunei Darussalam','BN',0)
,(NULL,'Bulgaria','BG',0)
,(NULL,'Burkina Faso','BF',0)
,(NULL,'Burundi','BI',0)
,(NULL,'Cambodia','KH',0)
,(NULL,'Cameroon','CM',0)
,(NULL,'Canada','CA',0)
,(NULL,'Cape Verde','CV',0)
,(NULL,'Cayman Islands','KY',0)
,(NULL,'Central African Republic','CF',0)
,(NULL,'Chad','TD',0)
,(NULL,'Chile','CL',0)
,(NULL,'China','CN',0)
,(NULL,'Christmas Island','CX',0)
,(NULL,'Cocos (Keeling) Islands','CC',0)
,(NULL,'Colombia','CO',0)
,(NULL,'Comoros','KM',0)
,(NULL,'Congo','CG',0)
,(NULL,'Cook Islands','CK',0)
,(NULL,'Costa Rica','CR',0)
,(NULL,"Cote D'Ivoire",'CI',0)
,(NULL,'Croatia','HR',0)
,(NULL,'Cuba','CU',0)
,(NULL,'Cyprus','CY',0)
,(NULL,'Czech Republic','CZ',0)
,(NULL,'Denmark','DK',0)
,(NULL,'Djibouti','DJ',0)
,(NULL,'Dominica','DM',0)
,(NULL,'Dominican Republic','DO',0)
,(NULL,'East Timor','TP',0)
,(NULL,'Ecuador','EC',0)
,(NULL,'Egypt','EG',0)
,(NULL,'El Salvador','SV',0)
,(NULL,'Equatorial Guinea','GQ',0)
,(NULL,'Eritrea','ER',0)
,(NULL,'Estonia','EE',0)
,(NULL,'Ethiopia','ET',0)
,(NULL,'Falkland Islands (Malvinas)','FK',0)
,(NULL,'Faroe Islands','FO',0)
,(NULL,'Fiji','FJ',0)
,(NULL,'Finland','FI',0)
,(NULL,'France','FR',0)
,(NULL,'French Guiana','GF',0)
,(NULL,'French Polynesia','PF',0)
,(NULL,'French Southern Territories','TF',0)
,(NULL,'Gabon','GA',0)
,(NULL,'Gambia','GM',0)
,(NULL,'Georgia','GE',0)
,(NULL,'Germany','DE',0)
,(NULL,'Ghana','GH',0)
,(NULL,'Gibraltar','GI',0)
,(NULL,'Greece','GR',0)
,(NULL,'Greenland','GL',0)
,(NULL,'Grenada','GD',0)
,(NULL,'Guadeloupe','GP',0)
,(NULL,'Guam','GU',0)
,(NULL,'Guatemala','GT',0)
,(NULL,'Guinea','GN',0)
,(NULL,'Guinea-bissau','GW',0)
,(NULL,'Guyana','GY',0)
,(NULL,'Haiti','HT',0)
,(NULL,'Heard and Mc Donald Islands','HM',0)
,(NULL,'Honduras','HN',0)
,(NULL,'Hong Kong','HK',0)
,(NULL,'Hungary','HU',0)
,(NULL,'Iceland','IS',0)
,(NULL,'India','IN',0)
,(NULL,'Indonesia','ID',0)
,(NULL,'Iran (Islamic Republic of)','IR',0)
,(NULL,'Iraq','IQ',0)
,(NULL,'Ireland','IE',0)
,(NULL,'Israel','IL',0)
,(NULL,'Italy','IT',0)
,(NULL,'Jamaica','JM',0)
,(NULL,'Japan','JP',0)
,(NULL,'Jordan','JO',0)
,(NULL,'Kazakhstan','KZ',0)
,(NULL,'Kenya','KE',0)
,(NULL,'Kiribati','KI',0)
,(NULL,"Korea, Democratic People's Republic of",'KP',0)
,(NULL,'Korea, Republic of','KR',0)
,(NULL,'Kuwait','KW',0)
,(NULL,'Kyrgyzstan','KG',0)
,(NULL,"Lao People's Democratic Republic",'LA',0)
,(NULL,'Latvia','LV',0)
,(NULL,'Lebanon','LB',0)
,(NULL,'Lesotho','LS',0)
,(NULL,'Liberia','LR',0)
,(NULL,'Libyan Arab Jamahiriya','LY',0)
,(NULL,'Liechtenstein','LI',0)
,(NULL,'Lithuania','LT',0)
,(NULL,'Luxembourg','LU',0)
,(NULL,'Macau','MO',0)
,(NULL,'Macedonia, The Former Yugoslav Republic of','MK',0)
,(NULL,'Madagascar','MG',0)
,(NULL,'Malawi','MW',0)
,(NULL,'Malaysia','MY',0)
,(NULL,'Maldives','MV',0)
,(NULL,'Mali','ML',0)
,(NULL,'Malta','MT',0)
,(NULL,'Marshall Islands','MH',0)
,(NULL,'Martinique','MQ',0)
,(NULL,'Mauritania','MR',0)
,(NULL,'Mauritius','MU',0)
,(NULL,'Mayotte','YT',0)
,(NULL,'Mexico','MX',0)
,(NULL,'Micronesia, Federated States of','FM',0)
,(NULL,'Moldova, Republic of','MD',0)
,(NULL,'Monaco','MC',0)
,(NULL,'Mongolia','MN',0)
,(NULL,'Montserrat','MS',0)
,(NULL,'Morocco','MA',0)
,(NULL,'Mozambique','MZ',0)
,(NULL,'Myanmar','MM',0)
,(NULL,'Namibia','NA',0)
,(NULL,'Nauru','NR',0)
,(NULL,'Nepal','NP',0)
,(NULL,'Netherlands','NL',0)
,(NULL,'Netherlands Antilles','AN',0)
,(NULL,'New Caledonia','NC',0)
,(NULL,'New Zealand','NZ',0)
,(NULL,'Nicaragua','NI',0)
,(NULL,'Niger','NE',0)
,(NULL,'Nigeria','NG',0)
,(NULL,'Niue','NU',0)
,(NULL,'Norfolk Island','NF',0)
,(NULL,'Northern Mariana Islands','MP',0)
,(NULL,'Norway','NO',0)
,(NULL,'Oman','OM',0)
,(NULL,'Pakistan','PK',0)
,(NULL,'Palau','PW',0)
,(NULL,'Panama','PA',0)
,(NULL,'Papua New Guinea','PG',0)
,(NULL,'Paraguay','PY',0)
,(NULL,'Peru','PE',0)
,(NULL,'Philippines','PH',0)
,(NULL,'Pitcairn','PN',0)
,(NULL,'Poland','PL',0)
,(NULL,'Portugal','PT',0)
,(NULL,'Puerto Rico','PR',0)
,(NULL,'Qatar','QA',0)
,(NULL,'Reunion','RE',0)
,(NULL,'Romania','RO',0)
,(NULL,'Russian Federation','RU',0)
,(NULL,'Rwanda','RW',0)
,(NULL,'Saint Kitts and Nevis','KN',0)
,(NULL,'Saint Lucia','LC',0)
,(NULL,'Saint Vincent and the Grenadines','VC',0)
,(NULL,'Samoa','WS',0)
,(NULL,'San Marino','SM',0)
,(NULL,'Sao Tome and Principe','ST',0)
,(NULL,'Saudi Arabia','SA',0)
,(NULL,'Senegal','SN',0)
,(NULL,'Seychelles','SC',0)
,(NULL,'Sierra Leone','SL',0)
,(NULL,'Singapore','SG',0)
,(NULL,'Slovakia (Slovak Republic)','SK',0)
,(NULL,'Slovenia','SI',0)
,(NULL,'Solomon Islands','SB',0)
,(NULL,'Somalia','SO',0)
,(NULL,'South Africa','ZA',0)
,(NULL,'South Georgia and the South Sandwich Islands','GS',0)
,(NULL,'Spain','ES',0)
,(NULL,'Sri Lanka','LK',0)
,(NULL,'St. Helena','SH',0)
,(NULL,'St. Pierre and Miquelon','PM',0)
,(NULL,'Sudan','SD',0)
,(NULL,'Suriname','SR',0)
,(NULL,'Svalbard and Jan Mayen Islands','SJ',0)
,(NULL,'Swaziland','SZ',0)
,(NULL,'Sweden','SE',0)
,(NULL,'Switzerland','CH',0)
,(NULL,'Syrian Arab Republic','SY',0)
,(NULL,'Taiwan','TW',0)
,(NULL,'Tajikistan','TJ',0)
,(NULL,'Tanzania, United Republic of','TZ',0)
,(NULL,'Thailand','TH',0)
,(NULL,'Togo','TG',0)
,(NULL,'Tokelau','TK',0)
,(NULL,'Tonga','TO',0)
,(NULL,'Trinidad and Tobago','TT',0)
,(NULL,'Tunisia','TN',0)
,(NULL,'Turkey','TR',0)
,(NULL,'Turkmenistan','TM',0)
,(NULL,'Turks and Caicos Islands','TC',0)
,(NULL,'Tuvalu','TV',0)
,(NULL,'Uganda','UG',0)
,(NULL,'Ukraine','UA',0)
,(NULL,'United Arab Emirates','AE',0)
,(NULL,'United Kingdom','GB',0)
,(NULL,'United States','US',0)
,(NULL,'United States Minor Outlying Islands','UM',0)
,(NULL,'Uruguay','UY',0)
,(NULL,'Uzbekistan','UZ',0)
,(NULL,'Vanuatu','VU',0)
,(NULL,'Vatican City State (Holy See)','VA',0)
,(NULL,'Venezuela','VE',0)
,(NULL,'Viet Nam','VN',0)
,(NULL,'Virgin Islands (British)','VG',0)
,(NULL,'Virgin Islands (U.S.)','VI',0)
,(NULL,'Wallis and Futuna Islands','WF',0)
,(NULL,'Western Sahara','EH',0)
,(NULL,'Yemen','YE',0)
,(NULL,'The Democratic Republic of Congo','DC',0)
,(NULL,'Zambia','ZM',0)
,(NULL,'Zimbabwe','ZW',0)
,(NULL,'East Timor','XE',0)
,(NULL,'Jersey','XJ',0)
,(NULL,'St. Barthelemy','XB',0)
,(NULL,'St. Eustatius','XU',0)
,(NULL,'Canary Islands','XC',0)
,(NULL,'Serbia','RS',0)
,(NULL,'Sint Maarten (French Antilles)','MF',0)
,(NULL,'Sint Maarten (Netherlands Antilles)','SX',0)
;
